version: '3.8'

services:
  hub:
    build: ./hub
    ports:
      - "8000:8000"
    volumes:
      - ./hub/missions:/app/missions
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - agent-network

  agent-claude:
    build: ./agent-claude
    ports:
      - "8001:8001"
    volumes:
      - ./agent-claude:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - agent-network
    depends_on:
      - hub


networks:
  agent-network:
    driver: bridge